### ISSUE TITLE
Can You share a dataset?

### ISSUE THREAD

**Issue by exousiayk** [Samia067/ShoeRinsics#2]
I was very impressed with your thesis. 

So I was also trying to experiment using the mitsuba tool. 

But I couldn't find the dataset.(in [62])

can you share the first 387 dataset?

**Comment by Samia067** [comment]
Thank you. I am happy to see you working in this area. The dataset with the 387 impressions is unfortunately not mine to share. You can reach out to the authors to see if they can share it.
